# Generated by Django 3.1.3 on 2022-01-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
