# Generated by Django 3.1.3 on 2022-01-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=20)),
                ('cost_aprox', models.IntegerField()),
                ('model', models.CharField(max_length=15)),
                ('date_origin', models.DateField()),
            ],
        ),
    ]
